### ISSUE TITLE
I can't export to PDF on my Mac M1

### ISSUE THREAD

**Issue by linhduongtuan** [Cubxity/typstudio#12] opened 2023-05-09 03:08 UTC
Hi @Cubxity,
I am a fan of TypStudio and I have installed and used it on my Mac M1. However, I have encountered a problem with exporting my file to pdf format on my Mac M1. I would appreciate any assistance or advice on how to solve this issue. 
Thank you for your time and attention.
Linh

**Comment by Cubxity** [comment] 2023-05-09 06:44
Could you be more specific about your issue? Please describe the actions taken. Any logs would also be helpful.

**Comment by caoimhebyrne** [comment] 2023-05-09 17:59
I'm unable to reproduce this with the following file, @linhduongtuan:
```typst
= Hello world
This is a test document, that I am using to test the export function in Typstudio
```

<img width="1607" alt="image" src="https://github.com/Cubxity/typstudio/assets/71222289/3a35b874-5283-4932-98ee-0176c7c0daac">

**Comment by Cubxity** [comment] 2023-05-09 21:25
Closing as the issue is irreproducible.

**Closed** 2023-05-09 21:26 UTC
