### ISSUE TITLE
Some small bugs I noticed

### ISSUE THREAD

**Issue by Okkonen-GitHub** [Cubxity/typstudio#16] opened 2023-05-13 10:57 UTC
I hope you don't mind that I made this just one issue.
1. `cancel(...)` doesn't seem to work
2. the wiggly line under where the error is often in the wrong place (or even on the wrong row)
3. `dot` by default is not the same as `dot.c` even though this is the default behavior in the online editor. (But I get if this is not seen as a problem)

**Comment by Cubxity** [comment] 2023-05-13 18:25
Issue 1 and 3 is fixed in https://github.com/Cubxity/typstudio/commit/3f8af911fe9c95b3d433949a67965700c2495d39. The `typst` version was outdated due to https://github.com/typst/typst/issues/930. I am unable to reproduce issue 2, please open a new issue with reproduction steps.

**Closed by Cubxity** 2023-05-13 18:25 UTC
